linters:
  enable-all: true
  disable:
    # re-enable when working in go1.18
    - bodyclose
    - contextcheck
    - gosimple
    - interfacer
    - nilerr
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - stylecheck
    - tparallel
    - unparam
    - unused
    - wastedassign
    # maybe enable these
    - wrapcheck
    # leave these disabled
    - containedctx
    - cyclop
    - deadcode
    - dupl
    - exhaustivestruct
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gocognit
    - goconst
    - godox
    - golint
    - gomnd
    - ifshort
    - lll
    - maligned
    - nestif
    - nlreturn
    - nosnakecase
    - scopelint
    - thelper
    - varcheck
    - varnamelen
